export const CONFIG = {
  SUPABASE_URL: "https://YOUR_PROJECT.supabase.co",
  SUPABASE_ANON_KEY: "PASTE_SUPABASE_ANON_KEY",
  GAME_WIDTH: 1600,
  GAME_HEIGHT: 900,
  TILE: 16,
  SCALE: 3,
  WORLD_WIDTH: 120,
  WORLD_HEIGHT: 80,
  PLAYER_SPEED: 130,
  PRESENCE_THROTTLE_MS: 100,
  CHAT_LIMIT: 60,
};
